config/routes.rb
Rails.application.routes.draw do
  get 'companionships/index'

  resources :companionships do
    resources :appointments
  end
  get '/companionships/:companionship_id/appointments/:date/new', to: 'appointments#new', as: :new_companionship_appointment_with_date

  get '/calendars/:id', to: 'calendars#show', as: :calendar_path
  get '/calendar', to: 'calendars#show_first', as: :calendar_default
  root 'calendars#show_first'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :companionship
  validates :date, presence: true
  validates :family, presence: true
end

app/models/companionship.rb
class Companionship < ApplicationRecord
  has_many :appointments, dependent: :destroy
  validates :label, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def index
    @appointments = Appointment.all
  end

  def create
    @companionship = Companionship.find(params[:companionship_id])
    @appointment = @companionship.appointments.create(appointment_params)
    redirect_to calendar_path_url(@companionship)
  end

  def edit
    @companionship = Companionship.find(params[:companionship_id])
    @appointment = Appointment.find(params[:id])
    @appointment_date = @appointment[:date]
  end

  def update
    @appointment = Appointment.find(params[:id])
    if @appointment.update(appointment_params)
      redirect_to calendar_path_url(@appointment.companionship)
    else
      render 'edit'
    end
  end

  def show
    @appointment = Appointment.find(params[:id])
  end

  def destroy
    @appointment = Appointment.find(params[:id])
    @appointment.destroy
    redirect_to calendar_path_url(@appointment.companionship[:id])
  end

  def new
    @companionship = Companionship.find(params[:companionship_id])
    @appointment_date = Date.parse params[:date]
  end

  private

  def appointment_params
    params.require(:appointment).permit(:date, :family, :contact_info, :other_info)
  end
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController

  def show
    @weeks = 6
    @dates = get_day_data(start_date, @weeks)
    @companionship = Companionship.find(params[:id])
    @companionships = Companionship.all.order(label: :asc)
    @appointments = @companionship.appointments
    @dates = populate_appts_data(@dates)
  end

  def show_first
    redirect_to controller: 'calendars', action: 'show', id: Companionship.all.first
  end

  def start_date
    Date.today.beginning_of_week(:sunday)
  end

  def get_day_data(start_date, num_weeks)
    dates_data = []
    (num_weeks * 7).times do |i|
      data = {}
      data[:date] = start_date + i
      data[:week_no] = i / 7
      data[:day_no] = i % 7
      dates_data << data
    end
    dates_data
  end

  def populate_appts_data(dates_data)
    @appointments.each do |appt|
      dates_data.map do |d|
        next if d.nil?

        next unless appt[:date] == d[:date]

        d[:date] = appt[:date]
        d[:family] = appt[:family]
        d[:contact_info] = appt[:contact_info]
        d[:other_info] = appt[:other_info]
        d[:appointment_id] = appt[:id]
      end
    end
    dates_data
  end
end

app/controllers/companionships_controller.rb
class CompanionshipsController < ApplicationController

  http_basic_authenticate_with name: "Ron", password: "welcome", except: [:show]

  def index
    @companionships = Companionship.all.order(id: :asc)
  end

  def edit
    @companionship = Companionship.find(params[:id])
  end

  def create
    @companionship = Companionship.new(companionship_params)

    @companionship.save
    redirect_to @companionship
  end

  def destroy
    @companionship = Companionship.find(params[:id])

    @companionship.destroy
    redirect_to companionships_path
  end

  def show
    @companionship = Companionship.find(params[:id])
  end

  def new
    @companionship = Companionship.new
  end

  def update
    @companionship = Companionship.find(params[:id])

    if @companionship.update(companionship_params)
      redirect_to @companionship
    else
      render 'edit'
    end
  end

  private
  def companionship_params
    params.require(:companionship).permit(:label)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/companionship_helper.rb
module CompanionshipHelper
end

app/views/appointments/_appointment.html.erb
<table>
  <tr>
    <th>Date</th>
    <th>Family</th>
    <th>Contact info</th>
    <th>Other</th>
  </tr>
  <% @companionship.appointments.order(date: :asc).each do |appointment| %>
    <tr>
      <td>
        <%= appointment.date %>
      </td>
      <td>
        <%= link_to "#{appointment.family}",  edit_companionship_appointment_path(@companionship, appointment)  %>
      </td>
      <td>
        <%= appointment.contact_info %>
      </td>
      <td>
        <%= appointment.other_info %>
      </td>
      <td>
        <%= link_to 'Edit', edit_companionship_appointment_path(@companionship, appointment) %>
      </td>
    </tr>
  <% end %>

app/views/appointments/_form.html.erb
<h2>Feed the
<%= @companionship.label %>
</h2>

<h3>
  <%= @appointment_date.strftime('%A %b %-d, %Y') %>
</h3>

<%= form_with(model: [ @companionship, @companionship.appointments.build ], local: true) do |form| %>
<p>
  <%= form.hidden_field :date, value: params[:date]%>
</p>
<p>
  <%= form.label(:family,:autofocus => true, class: '') %><br>
  <%= form.text_field :family %>
</p>
<p>
  <%= form.label :contact_info %><br>
  <%= form.text_field :contact_info %>
</p>
<p>
  <%= form.label :other_info %><br>
  <%= form.text_field :other_info %>
</p>

<p>
  <%= link_to "Cancel", :back, {:class=>"btn btn-secondary"} %>
  <%= form.submit("Create Appointment", :class=> "btn btn-primary") %>
</p>

<% end %>

app/views/appointments/_form_edit.html.erb
<h2>Feed the
<%= @companionship.label %>
</h2>
<h3>
  <%= @appointment_date.strftime('%A %b %-d, %Y') %>
</h3>

<%= form_with(model: [ @companionship, @appointment], local: true) do |form| %>
  <input name="_method" type="hidden" value="patch" />

 <p>
   <%= form.hidden_field :date, value: @appointment[:date]%>
 </p>
 <p>
   <%= form.label :family %><br>
   <%= form.text_field :family, :autofocus => true,  value: (@appointment[:family])  %>
 </p>
 <p>
   <%= form.label :contact_info %><br>
   <%= form.text_field :contact_info, value: (@appointment[:contact_info]) %>
 </p>
 <p>
   <%= form.label :other_info %><br>
   <%= form.text_field :other_info, value: (@appointment[:other_info]) %>
 </p>

  <p>
    <%= link_to "Cancel", :back, {:class=>"btn btn-secondary"} %>
      <%= (link_to '<i class="fas fa-trash-alt"></i> Delete'.html_safe, companionship_appointment_path(@companionship,@appointment),
             method: :delete,
             data: {confirm: 'Are you sure you want to delete this appointment? This action cannot be undone.'},
             :class => "btn btn-secondary"
           )
      %>
      <%= form.submit("Save Changes", :class=> "btn btn-primary") %>
  </p>
<% end %>

app/views/appointments/edit.html.erb
<%= render '/appointments/form_edit' %>

app/views/appointments/index.html.erb
<h1>All Appointments</h1>

<table class = 'appointment-table'>
  <tr>
    <th>Label</th>
    <th></th>
  </tr>

  <% @appointments.each do |appointment| %>
    <tr>
      <td class = 'companionship'><%= appointment.companionship.label %></td>
      <td class = 'date'><%= appointment.date %></td>
      <td class = 'family'><%= appointment.family %></td>
      <td class = 'contact'><%= appointment.contact_info %></td>
      <td class = 'other'><%= appointment.other_info %></td>
  <% end %>
</table>

app/views/appointments/new.html.erb
<%= render '/appointments/form' %>

app/views/appointments/show.html.erb
<h1>Appointment</h1>
<table class = 'appointment-table'>
  <tr>
    <th>Companionship</th>
    <th>Date</th>
    <th>Family</th>
    <th>Contact</th>
    <th>Other</th>
  </tr>
    <tr>
      <td class = 'companionship'><%= @appointment.companionship.label %></td>
      <td class = 'date'><%= @appointment.date %></td>
      <td class = 'family'><%= @appointment.family %></td>
      <td class = 'contact'><%= @appointment.contact_info %></td>
      <td class = 'other'><%= @appointment.other_info %></td>
</table>

app/views/calendars/show.html.erb
<h4>Forest Heights/Strathcona Missionary Meal Calendar</h4>

<!-- <form>
  <input class="d-print-none" type="button" value="Print" onclick="window.print()" />
</form> -->
<ul class="nav nav-tabs">
  <% @companionships.each do |comp| %>
    <li class="nav-item">
      <a class="nav-link d-print-none <%= 'active d-print-inline' if comp.id.to_s == params[:id] %>" href="<%= calendar_path_url(comp.id) %>"><%= comp.label %></a>
  <% end %>
  </li>
</ul>

  <table id = 'calendar' class = 'calendar-table table table-bordered table-responsive'>
    <thead class = 'table-active'>
      <tr>
        <% @dates.take(7).each do |day| %>
        <th class='calendar-header sticky-top'><%= day[:date].strftime("%A") %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @weeks.times do |week| %>
      <tr class="calendar-row">
        <% @dates.select { |h| h[:week_no] == week }.each do |day| %>
        <td class = 'calendar-cell p-0 <%= 'signed-up' if day[:family] %>'>
          <div class="card border-0 p-0">
            <div class = 'card-header calendar-date p-0 m-0 text-right'><%= day[:date].strftime("%b %-d") %> </div>
            <div class="card-body p-1 text-secondary <%= 'signed-up' if day[:family] %> ">
              <% if day[:family] %>
              <div class = 'card-text appt-data family'><%= day[:family] %> </div>
              <div class = 'card-text appt-data contact'><%= day[:contact_info] %> </div>
              <div class = 'card-text appt-data other'><%= day[:other_info] %> </div>
              <div class = 'card-text text-right d-print-none'>
                <%= link_to '<i class="fas fa-edit"></i> Edit'.html_safe, edit_companionship_appointment_path(@companionship, day[:appointment_id]) %> </div>
                <% else %>
                <div class = 'appt-none  d-print-none'><%= link_to '<i class="fas fa-calendar-plus"></i> Sign Up'.html_safe, new_companionship_appointment_with_date_path(@companionship, day[:date]) %></div>
                <% end %>
                <!-- <div> Week Number:<%= day[:week_no] %></div>
                  <div> Day Number:<%= day[:day_no] %></div> -->
                </div>
              </div>
            </td>
            <% end %>
          </tr>
          <% end %>
    </tbody>
  </table>
</div>

app/views/companionships/edit.html.erb
  <h1>Edit Companionship</h1>
  <%= form_with(model: @companionship, local: true) do |form| %>
    <p>
      <%= form.label :label %><br>
      <%= form.text_field :label %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>
  <%= link_to 'cancel', controller: 'companionships' %>

app/views/companionships/index.html.erb
<h1>Companionships</h1>

    <div class="table-bordered rounded">
      <table class = 'companionships-table'>

          <tr>
            <th>Companionship</th>
          </tr>
          <% @companionships.each do |companionship| %>
            <tr>
              <td class = 'label'><%= companionship.label %></td>
              <td><%=link_to 'Calendar', calendar_path_url(companionship) %></td>
              <td class = 'show'><%= link_to 'Appointment List', companionship_path(companionship) %></td>
              <td class = 'edit'><%= link_to 'Edit', edit_companionship_path(companionship) %></td>
              <td class = 'delete'><%= link_to 'Delete', companionship_path(companionship),
                                    method: :delete,
                                    data: {confirm: 'Are you sure you want to delete this companionship? All associated appointments will also be deleted'}
                                    %></td>
            </tr>
          <% end %>
      </table>
    </div>
    <%= link_to '<i class="fas fa-plus"></i> Create new Companionship'.html_safe, new_companionship_path %>

app/views/companionships/new.html.erb
<h1>New Companionship</h1>
<p>Create a new companionship</p>

<%= form_with scope: :companionship, url: :companionships, local: true do |form| %>
  <p>
    <%= form.label :label %><br>
    <%= form.text_field :label %>
  </p>
  <p>
    <%= link_to 'cancel', controller: 'companionships' %>
    <%= form.submit %>
  </p>
<% end %>

app/views/companionships/show.html.erb
<h1>Companionship</h1>
<h2>
  <%= @companionship.label %>
</h2>

<h2>Current Appointments</h2>

<%= render '/appointments/appointment' %>

<%= link_to 'view all', controller: 'companionships' %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-light container">
  <div class="btn btn-outline-secondary">
    <%= link_to 'Calendar', calendar_default_path %>
  </div>
  <div class="btn btn-outline-secondary">
    <%= link_to 'Companionships', companionships_path %>
  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amulek</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "application", media: "print" %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container col-sm-12 col-md-12 col-lg-12 col-xl-11">
    <%=yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>